---
# File to config rasberry pis
# references
# https://www.raspberrypi.org/documentation/configuration/config-txt/
# you need to copy your ssh keys to the pi in order for this to work
#
# Run the command below
# ansible-playbook -i inventories/hosts -u pi config_pi.yml
# You must cd to the Ansible directory

- hosts: pis
  become: yes
  gather_facts: true

  vars:
    # How this will show up on your router
    - hostname: steamlink-pi
    - overclock: yes
    # versions: zero, 3a+, 3b, 3b+, 4b, etc
    # I don't have a profile for every PI
    #
    # Used to select the overclock profile
    # this value is also appened to hostname; however, hostname
    # doesn't accept special characters
    - pi_model: 3bplus


  pre_tasks:
    - debug:
        msg: "WARNING!!! Adding Overclock profile for pi model {{ pi_model }}... Make sure a heatsync and fan are installed!"
      when: overclock

    - name: Set Timezone to America/New_York
      timezone:
        name: America/New_York

    - name: Install system packages
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - wget
        - nano
        - curl
        - rsync
        - vim
        - git
        - zip
        - sysbench # for overclocking

  # Role inspired by: https://www.youtube.com/watch?v=vjWGQDqUn2c&t
  # this worked for me
  # Some config borrowed from here:
  # Source: https://raspberrypi.stackexchange.com/questions/28907/how-could-one-automate-the-raspbian-raspi-config-setup
  tasks:
    - name: copy .bash_profile to ~/
      copy:
        src: .bash_profile
        dest: /home/pi/
        force: yes

    - name: Update Hostname of the Pi
      template:
        src: hostname.j2
        dest: /etc/hostname
        force: yes

    - name: copy overclock_profiles.txt to ~/
      copy:
        src: overclock_profiles.txt
        dest: /home/pi/
        force: yes

    # This is required for steamlink to work correctly
    - name: Enable boot wait, Allows network to connect before pi loads OS
      become: yes
      command: raspi-config nonint do_boot_wait 0

    # https://www.raspberrypi.org/documentation/configuration/config-txt/memory.md
    # Boostig gpu_mem is recommended for smooth operation of steamlink
    # If overclocking this setting will be overwritten,
    # therefore, we add this to each overclock profile
    - name: Adjusting GPU Memory
      become: yes
      blockinfile:
        path: /boot/config.txt
        block: |
          # gpu settings for steamlink
          gpu_mem_1024=512

    - include: overclock.yml
      when: overclock

    - name: install steamlink
      package:
          name: steamlink
          state: present
          update_cache: yes

    - name: enable steamlink autostart
      become: yes
      blockinfile:
        path: /etc/xdg/lxsession/LXDE-pi/autostart
        block: |
          steamlink

  post_tasks:
    - name: reboot PIs
      reboot:
